name: movam
description: Movam Map Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  config:
    path: packages/config
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  geolocator: ^8.0.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

